services:
  app:
    container_name: clothcast-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
